// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBYAZd3wrnX60kvwpsAT7ntlsOG0dQT6Q',
    appId: '1:610831232863:web:217c05132f40209e2790ea',
    messagingSenderId: '610831232863',
    projectId: 'your-supporter-3a11b',
    authDomain: 'your-supporter-3a11b.firebaseapp.com',
    storageBucket: 'your-supporter-3a11b.firebasestorage.app',
    measurementId: 'G-E6CW1H5ST6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPGHKtH5GvQd7ZwzpC1FtSPArKPtWKsvc',
    appId: '1:610831232863:android:ed35ffe89ffc7e1c2790ea',
    messagingSenderId: '610831232863',
    projectId: 'your-supporter-3a11b',
    storageBucket: 'your-supporter-3a11b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzV6QCbHGT-bmOn0KV-7eYVQBxvEAkdvM',
    appId: '1:610831232863:ios:915113e063a4dcce2790ea',
    messagingSenderId: '610831232863',
    projectId: 'your-supporter-3a11b',
    storageBucket: 'your-supporter-3a11b.firebasestorage.app',
    iosBundleId: 'com.example.yourSupporter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzV6QCbHGT-bmOn0KV-7eYVQBxvEAkdvM',
    appId: '1:610831232863:ios:915113e063a4dcce2790ea',
    messagingSenderId: '610831232863',
    projectId: 'your-supporter-3a11b',
    storageBucket: 'your-supporter-3a11b.firebasestorage.app',
    iosBundleId: 'com.example.yourSupporter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBYAZd3wrnX60kvwpsAT7ntlsOG0dQT6Q',
    appId: '1:610831232863:web:391bea885c875ddf2790ea',
    messagingSenderId: '610831232863',
    projectId: 'your-supporter-3a11b',
    authDomain: 'your-supporter-3a11b.firebaseapp.com',
    storageBucket: 'your-supporter-3a11b.firebasestorage.app',
    measurementId: 'G-E8YPDBH2DV',
  );
}